version: '3.7'

services:
  storage-service:
    container_name: str
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: storage-service
    networks:
      - storage-service-network
      - todo-app-network
    command: "npm run debug"
    environment:
      - INTERNAL_PORT=3000
      - EXTERNAL_PORT=8000
      - DEBUG_PORT=9229
    volumes:
      - ./app:/app
      - client-storage:/client-storage 
      - quarantine-storage:/quarantine-storage
    ports:
      - 8000:3000
      - 9200:9229
    depends_on:
      - storage-service-db

  storage-worker:
    container_name: storage-worker
    build: 
      context: ./worker/
      dockerfile: ./Dockerfile
    image: storage-worker
    command: "tail -f /dev/null"
    networks:
      - storage-service-network
      - todo-app-network
    environment:
      - INTERNAL_PORT=3000
      - EXTERNAL_PORT=8001
      - DEBUG_PORT=9229
    volumes:
      - "./worker/src:/app"
      - quarantine-storage:/quarantine-storage
    ports:
      - 8001:3000
      - 9201:9229
    depends_on:
      - storage-service

  storage-service-db:
    container_name: storage-service-db
    image: postgres:13.5-alpine
    networks:
      - storage-service-network
    volumes:
      - storage-service-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=file_storage
      - POSTGRES_USER=file_user
      - POSTGRES_PASSWORD=test1234

networks:
  storage-service-network:
    name: storage-service-network
  todo-app-network:
    name: todo-app-network

volumes:
  storage-service-db-vol:
    name: storage-service-db-vol
  client-storage: 
    name: client-storage
  quarantine-storage: 
    name: quarantine-storage