export default mimeTypes = [
    {"ext": ".aac", "description" : "AAC audio", "mime": "audio/aac"},
    {"ext": ".mid", "description" : "Musical Instrument Digital Interface (MIDI)", "mime": "audio/midi"},
    {"ext": ".midi", "description" : "Musical Instrument Digital Interface (MIDI)", "mime": "audio/x-midi"},
    {"ext": ".mp3", "description" : "MP3 audio", "mime": "audio/mpeg"},
    {"ext": ".oga", "description" : "OGG audio", "mime": "audio/ogg"},
    {"ext": ".opus", "description" : "Opus audio", "mime": "audio/opus"},
    {"ext": ".weba", "description" : "WEBM audio", "mime": "audio/webm"},
    {"ext": ".wav", "description" : "Waveform Audio Format", "mime": "audio/wav"},
    {"ext": ".3gp", "description" : "3GPP audio container", "mime": "audio/3gpp"},
    {"ext": ".3g2", "description" : "3GPP2 audio container", "mime": "audio/3gpp2"},
    {"ext": ".3g2", "description" : "3GPP2 video container", "mime": "video/3gpp2"},
    {"ext": ".3gp", "description" : "3GPP video container", "mime": "video/3gpp"},
    {"ext": ".abw", "description" : "AbiWord document", "mime": "application/x-abiword"},
    {"ext": ".arc", "description" : "Archive document (multiple files embedded)", "mime": "application/x-freearc"},
    {"ext": ".avi", "description" : "AVI: Audio Video Interleave", "mime": "video/x-msvideo"},
    {"ext": ".azw", "description" : "Amazon Kindle eBook format", "mime": "application/vnd.amazon.ebook"},
    {"ext": ".bin", "description" : "Any kind of binary data", "mime": "application/octet-stream"},
    {"ext": ".bmp", "description" : "Windows OS/2 Bitmap Graphics", "mime": "image/bmp"},
    {"ext": ".bz", "description" : "BZip archive", "mime": "application/x-bzip"},
    {"ext": ".bz2", "description" : "BZip2 archive", "mime": "application/x-bzip2"},
    {"ext": ".cda", "description" : "CD audio", "mime": "application/x-cdf"},
    {"ext": ".csh", "description" : "C-Shell script", "mime": "application/x-csh"},
    {"ext": ".css", "description" : "Cascading Style Sheets (CSS)", "mime": "text/css"},
    {"ext": ".csv", "description" : "Comma-separated values (CSV)", "mime": "text/csv"},
    {"ext": ".doc", "description" : "Microsoft Word", "mime": "application/msword"},
    {"ext": ".docx", "description" : "Microsoft Word (OpenXML)", "mime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
    {"ext": ".eot", "description" : "MS Embedded OpenType fonts", "mime": "application/vnd.ms-fontobject"},
    {"ext": ".epub", "description" : "Electronic publication (EPUB)", "mime": "application/epub+zip"},
    {"ext": ".gz", "description" : "GZip Compressed Archive", "mime": "application/gzip"},
    {"ext": ".gif", "description" : "Graphics Interchange Format (GIF)", "mime": "image/gif"},
    {"ext": ".htm .html", "description" : "HyperText Markup Language (HTML)", "mime": "text/html"},
    {"ext": ".ico", "description" : "Icon format", "mime": "image/vnd.microsoft.icon"},
    {"ext": ".ics", "description" : "iCalendar format", "mime": "text/calendar"},
    {"ext": ".jar", "description" : "Java Archive (JAR)", "mime": "application/java-archive"},
    {"ext": ".jpeg .jpg", "description" : "JPEG images", "mime": "image/jpeg"},
    {"ext": ".js", "description" : "JavaScript", "mime": "text/javascript"},
    {"ext": ".json", "description" : "JSON format", "mime": "application/json"},
    {"ext": ".jsonld", "description" : "JSON-LD format", "mime": "application/ld+json"},
    {"ext": ".mjs", "description" : "JavaScript module", "mime": "text/javascript"},
    {"ext": ".mp4", "description" : "MP4 video", "mime": "video/mp4"},
    {"ext": ".mpeg", "description" : "MPEG Video", "mime": "video/mpeg"},
    {"ext": ".mpkg", "description" : "Apple Installer Package", "mime": "application/vnd.apple.installer+xml"},
    {"ext": ".odp", "description" : "OpenDocument presentation document", "mime": "application/vnd.oasis.opendocument.presentation"},
    {"ext": ".ods", "description" : "OpenDocument spreadsheet document", "mime": "application/vnd.oasis.opendocument.spreadsheet"},
    {"ext": ".odt", "description" : "OpenDocument text document", "mime": "application/vnd.oasis.opendocument.text"},
    {"ext": ".ogv", "description" : "OGG video", "mime": "video/ogg"},
    {"ext": ".ogx", "description" : "OGG", "mime": "application/ogg"},
    {"ext": ".otf", "description" : "OpenType font", "mime": "font/otf"},
    {"ext": ".png", "description" : "Portable Network Graphics", "mime": "image/png"},
    {"ext": ".pdf", "description" : "Adobe Portable Document Format (PDF)", "mime": "application/pdf"},
    {"ext": ".php", "description" : "Hypertext Preprocessor (Personal Home Page)", "mime": "application/x-httpd-php"},
    {"ext": ".ppt", "description" : "Microsoft PowerPoint", "mime": "application/vnd.ms-powerpoint"},
    {"ext": ".pptx", "description" : "Microsoft PowerPoint (OpenXML)", "mime": "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
    {"ext": ".rar", "description" : "RAR archive", "mime": "application/vnd.rar"},
    {"ext": ".rtf", "description" : "Rich Text Format (RTF)", "mime": "application/rtf"},
    {"ext": ".sh", "description" : "Bourne shell script", "mime": "application/x-sh"},
    {"ext": ".svg", "description" : "Scalable Vector Graphics (SVG)", "mime": "image/svg+xml"},
    {"ext": ".swf", "description" : "Small web format (SWF) or Adobe Flash document", "mime": "application/x-shockwave-flash"},
    {"ext": ".tar", "description" : "Tape Archive (TAR)", "mime": "application/x-tar"},
    {"ext": ".tif .tiff", "description" : "Tagged Image File Format (TIFF)", "mime": "image/tiff"},
    {"ext": ".ts", "description" : "MPEG transport stream", "mime": "video/mp2t"},
    {"ext": ".ttf", "description" : "TrueType Font", "mime": "font/ttf"},
    {"ext": ".txt", "description" : "Text, (generally ASCII or ISO 8859-n)", "mime": "text/plain"},
    {"ext": ".vsd", "description" : "Microsoft Visio", "mime": "application/vnd.visio"},
    {"ext": ".webm", "description" : "WEBM video", "mime": "video/webm"},
    {"ext": ".webp", "description" : "WEBP image", "mime": "image/webp"},
    {"ext": ".woff", "description" : "Web Open Font Format (WOFF)", "mime": "font/woff"},
    {"ext": ".woff2", "description" : "Web Open Font Format (WOFF)", "mime": "font/woff2"},
    {"ext": ".xhtml", "description" : "XHTML", "mime": "application/xhtml+xml"},
    {"ext": ".xls", "description" : "Microsoft Excel", "mime": "application/vnd.ms-excel"},
    {"ext": ".xlsx", "description" : "Microsoft Excel (OpenXML)", "mime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
    {"ext": ".xml", "description" : "XML", "mime": "application/xml is recommended as of RFC 7303 (section 4.1), but text/xml is still used sometimes. You can assign a specific MIME type to a file with .xml extension depending on how its contents are meant to be interpreted. For instance, an Atom feed is application/atom+xml, but application/xml serves as a valid default."},
    {"ext": ".xul", "description" : "XUL", "mime": "application/vnd.mozilla.xul+xml"},
    {"ext": ".zip", "description" : "ZIP archive", "mime": "application/zip"},
    {"ext": ".7z", "description" : "7-zip archive", "mime": "application/x-7z-compressed"}
];